### ISSUE TITLE
Fatal error: Class 'GuzzleHttp\Client' not found in <my test script>

### ISSUE THREAD

**Issue by normd** [SparkPost/php-sparkpost#37]
Asking for a friend. Followed the instructions in the readme, but get "Fatal error: Class 'GuzzleHttp\Client' not found in /Users/some_user/sparktest.php on line 8

sparktest.php is a local version of the test code at https://github.com/SparkPost/php-sparkpost#getting-started--your-first-mailing
that line is:
$httpAdapter = new Guzzle6HttpAdapter(new Client());

**Comment by max-mathieu** [comment]
Are we sure they followed https://github.com/SparkPost/php-sparkpost#installation ? that should have installed the needed dependencies

**Comment by max-mathieu** [comment]
I believe you also need to install Guzzle itself
`php composer.phar require guzzlehttp/guzzle`
for that example to work

**Comment by beardyman** [comment]
So I read through the README and its not completely explicit.  The issue here seems to be documentation but basically for that example to work they'll have to install the guzzle client.  Those instructions are here: http://docs.guzzlephp.org/en/latest/overview.html#installation

I'll update the README to point that out more.

For reference: The idea is that they can take what ever request library they're using and pass it in.  That could be guzzle, curl, or any number of things/

**Comment by max-mathieu** [comment]
Same here

Also, the example in the readme has a typo (missing comma after substitutionData line) making it throw a parsing error)

**Comment by normd** [comment]
Thanks. I ran php composer.phar require guzzlehttp/guzzle and all was well.

**Comment by beardyman** [comment]
Cool.  I'm going to leave this issue open until I can address the README updates.  I'll try to do that tomorrow.
